### ISSUE TITLE
pip provided pymeshlab fails on CentOS-7 x86_64

### ISSUE THREAD

**Issue by truatpasteurdotfr** [cnr-isti-vclab/PyMeshLab#215]
```
(morphometrics) [truadm@santos 20220429]$ python3 -c 'import pymeshlab'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/esmmc/morphometrics/miniconda3/envs/morphometrics/lib/python3.9/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /esmmc/morphometrics/miniconda3/envs/morphometrics/lib/python3.9/site-packages/pymeshlab/pmeshlab.cpython-39-x86_64-linux-gnu.so)
```

**Comment by truatpasteurdotfr** [comment]
same as #157
