### ISSUE TITLE
ImportError: DLL load failed while importing pmeshlab

### ISSUE THREAD

**Issue by green-fish** [cnr-isti-vclab/PyMeshLab#254]
while i runing:
import pymeshlab

ms = pymeshlab.MeshSet ()
ms.load_new_mesh (ipath)
ms.save_current_mesh (opath)

The following error occor:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "..\Documents\Anaconda\lib\site-packages\pymeshlab\__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: DLL load failed while importing pmeshlab

after downloading the pmeshlab package from https://github.com/JeanMaximilienCadic/pmeshlab and drag the folder to the index, the following error occor:
ImportError: cannot import name 'Mesh' from partially initialized module 'pymeshlab' (most likely due to a circular import) (..\Documents\Anaconda\lib\site-packages\pymeshlab\__init__.py)

it would be appreciated if u have any solution~

**Comment by alemuntoni** [comment]
probably related to #47.
Are you installing through conda? Could you try the suggested solutions in the thread?
