### ISSUE TITLE
Importing matplotlib causes crash

### ISSUE THREAD

**Issue by marcomusy** [cnr-isti-vclab/PyMeshLab#275]
I noticed that order of importing the 2 libraries can cause this crash:
```
Traceback (most recent call last):
  File "/home/musy/Projects/vedo/examples/other/pymeshlab2.py", line 5, in <module>
    import matplotlib
  File "/home/musy/soft/anaconda3/lib/python3.9/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/musy/soft/anaconda3/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/musy/soft/anaconda3/lib/python3.9/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/musy/soft/anaconda3/lib/python3.9/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/musy/soft/anaconda3/lib/python3.9/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/musy/soft/anaconda3/lib/python3.9/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/musy/soft/anaconda3/lib/python3.9/site-packages/matplotlib/_path.cpython-39-x86_64-linux-gnu.so)
```

from simply:
```python
import pymeshlab
import matplotlib
```

with:
`pymeshlab==2022.2.post2`
`matplotlib==3.5.2`
`numpy==1.21.6`

**Comment by alemuntoni** [comment]
This is again something that is going on while running pymeshlab from anaconda. I really don't know how to solve it, and we don't provide a conda package.
The code you shared works fine on a non-conda linux environment, using just pip to install the packages.
