### ISSUE TITLE
Import ERROR ----> from .pmeshlab import *

### ISSUE THREAD

**Issue by zhangquanwei962** [cnr-isti-vclab/PyMeshLab#282]
Hi, thank you for your great work! But when I use it, it reports a error like this:
```
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    from nerf.network_grid import NeRFNetwork
  File "/share/home/csttest15/zhangquanwei/stable-dreamfusion/nerf/network_grid.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "/share/home/csttest15/zhangquanwei/stable-dreamfusion/nerf/renderer.py", line 13, in <module>
    from meshutils import decimate_mesh, clean_mesh, poisson_mesh_reconstruction
  File "/share/home/csttest15/zhangquanwei/stable-dreamfusion/meshutils.py", line 2, in <module>
    import pymeshlab as pml
  File "/share/home/csttest15/miniconda3/envs/ldm/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /share/home/csttest15/miniconda3/envs/ldm/lib/python3.8/site-packages/pymeshlab/pmeshlab.cpython-38-x86_64-linux-gnu.so)

```
I find the pmeshlab not exist. Is it right? Thank you!

**Comment by alemuntoni** [comment]
hi, pymeshlab does not still support conda. You have to use it in a python environment.
