### ISSUE TITLE
[SOLVED]unable to run Transfer Vertex Properties to Texture filter

### ISSUE THREAD

**Issue by TokyoWarfare** [cnr-isti-vclab/PyMeshLab#286]
Hello,

With the help of chatGPT I got till this script, it goes till it runs the filter but the filter fails, all the params are fed as per the documentation but I guet the error I paste below the code:

`import os
import pymeshlab as ml

# Set the paths for the input point cloud and output mesh folders
point_cloud_folder = "E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/color"
mesh_folder = "E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/mesh"
output_folder = "E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/output"

# Print the variable names and their values
print("point_cloud_folder:", point_cloud_folder)
print("mesh_folder:", mesh_folder)
print("output_folder:", output_folder)

# Loop through all files in the point cloud folder
for filename in os.listdir(point_cloud_folder):
    
    # Check if the file is a PLY file
    if filename.endswith(".ply"):
        
        # Construct the input and output file paths
        input_file = os.path.join(point_cloud_folder, filename)
        output_file = os.path.join(mesh_folder, os.path.splitext(filename)[0] + ".obj")
        # output_texture = os.path.join(output_folder, os.path.splitext(filename)[0] + ".png")# filename is the name only  must not be full path
        
        # Print the variable names and their values
        print("input_file:", input_file)
        print("output_file:", output_file)
        
        # Create a MeshSet object
        ms = ml.MeshSet()
        
        # Load the mesh from the OBJ file
        ms.load_new_mesh(output_file)
        
        # Transfer color attributes from the point cloud to the mesh texture
        ms.apply_filter('transfer_attributes_to_texture_per_vertex', sourcemesh=input_file, targetmesh=output_file,
                 attributeenum='Vertex Color', upperbound='Percentage=2%', textname=os.path.splitext(filename)[0] + ".png", 
                 textw=16384, texth=16384, overwrite=False, pullpush=True)
        
        # Save the modified mesh to the output folder
        ms.save_current_mesh(output_file)
`

This is the error : 

**(base) E:\LIDAR_JAPAN\MMS8_Prototype_3\MMS\03_RoadMesh\04_Texturing\test>python auto_texturing_text.py
point_cloud_folder: E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/color
mesh_folder: E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/mesh
output_folder: E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/output
input_file: E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/color\08OE2718.ply
output_file: E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/mesh\08OE2718.obj
Traceback (most recent call last):
  File "E:\LIDAR_JAPAN\MMS8_Prototype_3\MMS\03_RoadMesh\04_Texturing\test\auto_texturing_text.py", line 36, in <module>
    ms.apply_filter('transfer_attributes_to_texture_per_vertex', sourcemesh=input_file, targetmesh=output_file,
RuntimeError: Unable to cast Python instance to C++ type (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)**

I'm totally stuck :\

edit: files used in the test: 
https://drive.google.com/file/d/1Xa_Cs0Kx4N2svqKtDL9aaWvTQdcE0bXE/view?usp=share_link
edit2
I noticed that in the GUI there is a param "abs" that is missing the pyMeshLab, wonder if that could be the cause of the issue.

**Comment by TokyoWarfare** [comment]
after lookign on the web, seemed that this kind of err raised when passing not objects so I aked chatGPT to load the data with meshload and to store the values in variables and feed the Filter with the variables instead, yet seem that same keeps happening : 

`import os
import pymeshlab as ml

# Set the paths for the input point cloud and output mesh folders
point_cloud_folder = "E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/color"
mesh_folder = "E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/mesh"
output_folder = "E:/LIDAR_JAPAN/MMS8_Prototype_3/MMS/03_RoadMesh/04_Texturing/test/output"

# Print the variable names and their values
print("point_cloud_folder:", point_cloud_folder)
print("mesh_folder:", mesh_folder)
print("output_folder:", output_folder)

# Loop through all files in the point cloud folder
for filename in os.listdir(point_cloud_folder):

    # Check if the file is a PLY file
    if filename.endswith(".ply"):

        # Construct the input and output file paths
        input_file = os.path.join(point_cloud_folder, filename)
        output_file = os.path.join(mesh_folder, os.path.splitext(filename)[0] + ".obj")
        # output_texture = os.path.join(output_folder, os.path.splitext(filename)[0] + ".png")# filename is the name only  must not be full path

        # Print the variable names and their values
        print("input_file:", input_file)
        print("output_file:", output_file)

        # Load point cloud and mesh using ms.load_new_mesh
        ms = ml.MeshSet()
        point_cloud_mesh = ms.load_new_mesh(input_file)
        texture_mesh = ms.load_new_mesh(output_file)

        # Load the mesh from the OBJ file
        ms.load_new_mesh(output_file)

        # Transfer color attributes from the point cloud to the mesh texture
        ms.apply_filter('transfer_attributes_to_texture_per_vertex', sourcemesh=point_cloud_mesh, targetmesh=texture_mesh,
                         attributeenum='Vertex Color', upperbound='Percentage=2%', textname=os.path.splitext(filename)[0] + ".png",
                         textw=16384, texth=16384, overwrite=False, pullpush=True)

        # Save the modified mesh to the output folder
        ms.save_current_mesh(output_file)
`

**Comment by TokyoWarfare** [comment]
PROGRESS!!!

"  File "E:\LIDAR_JAPAN\MMS8_Prototype_3\zz_Batch_commands\MMS\04_d_auto_texturing_text.py", line 40, in <module>
    ms.apply_filter('transfer_attributes_to_texture_per_vertex', sourcemesh=0, targetmesh=1,
pymeshlab.pmeshlab.PyMeshLabException: Parameter upperbound: must be a pymeshlab.Percentage object or apymeshlab.AbsoluteValue object. Other type values are not accepted.
"

I was using as param for the meshes a variable instead of an int!!. 

ps: take chatGPT scripts with a grain of salt XD
