### ISSUE TITLE
Failed loading textures (only on Ubuntu!)

### ISSUE THREAD

**Issue by meJevin** [cnr-isti-vclab/PyMeshLab#294]
Hay, I've been using this wonderful library and while testing it on some models I found a weird issue:
I have an `.obj` model with one `.mtl` file, which references 3 texture files. 
When I use pymeshlab to load my `.obj` model in Windows (using `pymeshlab.MeshSet`), everything works perfectly, but when I load the same model in Ubuntu, it says it can't load textures!
Here are the logs from Windows:
![image](https://user-images.githubusercontent.com/16974717/233203516-c5414162-4722-4c27-af2f-325468d310ab.png)
And from Ubuntu:
![image](https://user-images.githubusercontent.com/16974717/233203769-9f578bb7-3faf-4528-9c93-8f818d6414e4.png)

I'm not an expert in Linux. Maybe, there's an issue with permissions on the `.jpg` files?
Here's an output of `ls` command:
![image](https://user-images.githubusercontent.com/16974717/233203933-ac7b61f4-38f7-4c5c-a349-18df24aebae4.png)

And, finally, here's the model:
[male02.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/11277738/male02.zip)

**Comment by meJevin** [comment]
I am using Ubuntu under WSL, by the way. But it's the same thing in a container using Ubuntu, which is where I use this code.

**Comment by meJevin** [comment]
Maybe we could provide more information when outputting the error?
I guess, we output it here?
https://github.com/cnr-isti-vclab/meshlab/blob/ea86d952f170b5e61dfb9f420bb9ef0671b6ffe7/src/common/ml_document/mesh_model.cpp#L121

**Comment by meJevin** [comment]
I studied the source code a little bit and decided to try this: I converted all the `.jpg` files in the `.zip` archive that I provided to `.png` format. I then replaced all the references to `.jpg` files in my `.mtl` file with my new `.png` images. Mesh loaded successfully! So, I guess it's a problem with `.jpg` image loading then?
I was looking through this code:
https://github.com/cnr-isti-vclab/meshlab/blob/108e98b7b6be34219cf05543e8aac1660adf03b3/src/common/utilities/load_save.cpp#L312

If my assumption is correct, is there a way I can troubleshoot why `.jpg` images are not loading?
Or maybe I'm missing some library in my Ubuntu? I've installed `libjpeg-dev`, didn't help.

**Comment by meJevin** [comment]
Tried installing a ton of other libs, no luck. Maybe it's an issue with Qt?

**Comment by Heroism502** [comment]
> Hay, I've been using this wonderful library and while testing it on some models I found a weird issue: I have an `.obj` model with one `.mtl` file, which references 3 texture files. When I use pymeshlab to load my `.obj` model in Windows (using `pymeshlab.MeshSet`), everything works perfectly, but when I load the same model in Ubuntu, it says it can't load textures! Here are the logs from Windows: ![image](https://user-images.githubusercontent.com/16974717/233203516-c5414162-4722-4c27-af2f-325468d310ab.png) And from Ubuntu: ![image](https://user-images.githubusercontent.com/16974717/233203769-9f578bb7-3faf-4528-9c93-8f818d6414e4.png)
> 
> I'm not an expert in Linux. Maybe, there's an issue with permissions on the `.jpg` files? Here's an output of `ls` command: ![image](https://user-images.githubusercontent.com/16974717/233203933-ac7b61f4-38f7-4c5c-a349-18df24aebae4.png)
> 
> And, finally, here's the model: [male02.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/11277738/male02.zip)

can you post your script ?

**Comment by h-silderhuis** [comment]
Had the same issue on Ubuntu when calling load_new_mesh from a .obj file.
Script was running fine on Windows, but couldn't load the .jpg files referenced in the .mtl file when deployed on Ubuntu, with Python 3.10 installed.

Code for reference:
```
import pymeshlab

ms = pymeshlab.MeshSet()

ms.set_verbosity(True)

ms.load_new_mesh('model_pv.obj') # Throws error
ms.set_texture(textname='model_pv.jpg') # Also throws error
```

Error on load_new_mesh:
`Failed loading model_pv.jpg; using a dummy texture`

Error on set_texture:
```
Applying filter set_texture with the following parameters:
{'textname': 'model_pv.jpg', 'use_dummy_texture': False}

Traceback (most recent call last):
  File "/home/metashape/Downloads/mesh_obj/test.py", line 8, in <module>
    ms.set_texture(textname='model_pv.jpg')
  File "/home/metashape/.local/lib/python3.10/site-packages/pymeshlab/__init__.py", line 41, in foo
    res_dict = self.apply_filter(name, **kwargs)
pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: set_texture
Details: Failed to load the image model_pv.jpg
```

**Comment by h-silderhuis** [comment]
Seems to be a problem on the newest version only, though.
When installing version 2021.10 (`sudo pip install pymeshlab==2021.10`) the problem is fixed.

**Comment by guizy67** [comment]
I'm having the same issue. I'm using a 'Set Texture' filter.
Error:
```
pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: set_texture_per_mesh
Details: Failed to load the image texture_1001.jpg
```
I've tested several versions from `pymeshlab-2022.2.post2` to the most recent. All versions after `2022.2.post2` are giving this error, `2022.2.post2` is working fine in exactly the same environment.
I'm using ubuntu LTS 22.04 and LTS 24.04. Both give the same error.

Looking at other issues it's seems there's a problem in other areas where textures and jpg files are concerned. Is there some library dependency or something?

Current workaround is to stick to `2022.2.post2` version.

**Comment by cmcfadden** [comment]
Just chiming in that I'm seeing this here as well, with a simple script that reads an `obj` and writes a `ply`

```
import pymeshlab
import sys
ms = pymeshlab.MeshSet()
conversion_type = sys.argv[1]
input_file = sys.argv[2]
output_file = sys.argv[3]
ms.load_new_mesh(input_file)
if(conversion_type == 'obj_to_ply'):
    ms.apply_filter('compute_color_from_texture_per_vertex')

ms.save_current_mesh(output_file)
```
