### ISSUE TITLE
std::bad_alloc exception when importing 

### ISSUE THREAD

**Issue by bpedazur** [cnr-isti-vclab/PyMeshLab#332]
I have an issue importing a large e57 file (2.7GB) on Ubuntu 22.04. 

I get the following error:

> Traceback (most recent call last):
>   File "pymeshlab-test.py", line 61, in <module>
>     example_save_mesh()
>   File "pymeshlab-test.py", line 52, in example_save_mesh
>     ms.load_new_mesh("myfile.e57")
> pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: myfile.e57
> std::bad_alloc

**Comment by alemuntoni** [comment]
Probably already solved. Could you please try the [latest nightly from the devel branch](https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-install-the-last-nightly-version) to see if the issue persists?
