### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ~/miniconda3x86/lib/python3.11/site-packages/pymeshlab/pmeshlab.cpython-311-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by jpainam** [cnr-isti-vclab/PyMeshLab#360]
```python
Successfully installed pymeshlab-2022.2.post3
(base) [~]$ python -c "import pymeshlab as p; ms = p.MeshSet(); ms.meshing_isotropic_explicit_remeshing()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/miniconda3x86/lib/python3.11/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ~/miniconda3x86/lib/python3.11/site-packages/pymeshlab/pmeshlab.cpython-311-x86_64-linux-gnu.so)
```

I used pymeshlab 1.21.2 or  0.1.7i have this error.

```python
Traceback (most recent call last):
  File "eval.py", line 451, in <module>
    ms.meshing_isotropic_explicit_remeshing()
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'meshing_isotropic_explicit_remeshing'
```

System info
```bash
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by alemuntoni** [comment]
As said in #157:
```
Our automatic build system runs on ubuntu18 since ubuntu16 is not supported anymore. There is not much more I can do.
If there is no way to update libstdc++, I think that the only way to have pymeshlab running on that system would be to build it manually.
```

The only difference is that right now, we are building on ubuntu 20.04 (and we will likely build only on ubuntu 22.04 next year).
Old pymeshlab packages did not have the check on GLIBC version, and that is the reason why the installation is successful.
But there is no way to run pymeshlab on a old version of GLIBC w.r.t. the one used to do the build.
