### ISSUE TITLE
OBJ files don't load textures in pymeshlab >2022.2

### ISSUE THREAD

**Issue by bedaberner** [cnr-isti-vclab/PyMeshLab#362]
When running the following code I get the expected result in pymeshlab 2022.2 and before.
However in later versions, the textures don't seem to be imported (no textures are copied to the output folder and the .mlp file contains only the mesh, no textures.)
```
import pymeshlab

ms = pymeshlab.MeshSet()
ms.load_new_mesh("example.obj")
ms.save_current_mesh("output/result.obj", save_vertex_color=True,save_vertex_normal=True,save_face_color=True,save_wedge_normal=True,save_polygonal=True,save_textures=True,texture_quality=-1)
ms.save_project("test.mlp")
```

**Comment by alemuntoni** [comment]
I cannot replicate the issue. When saving a mesh, also the texture is saved in my system and in my input mesh.
The mlp file not containing the textures is expected, since textures are associated with the mesh.
Could you please share your input file and your system setup?

**Comment by domef** [comment]
It stops working from [v2022.2.post3](https://github.com/cnr-isti-vclab/PyMeshLab/releases/tag/v2022.2.post3).

**Comment by guizy67** [comment]
I have a similar issue, also stops working after v2022.2.post2 (last working version).

Using `Set Texture` filter, this is the error:
```
Traceback (most recent call last):
  File "/home/guizy/Meshroom/v2023-3/filtermodel.py", line 33, in <module>
    ms.set_texture_per_mesh(textname = texturefile)
  File "/home/guizy/.local/lib/python3.10/site-packages/pymeshlab/__init__.py", line 41, in foo
    res_dict = self.apply_filter(name, **kwargs)
pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: set_texture_per_mesh
Details: Failed to load the image /home/guizy/Meshroom/v2023-3/Work/Curatio/texture_1001.jpg
```

**Comment by stellarpower** [comment]
I am able to load meshes fine in the GUI. When I load from python, I keep seeing it replaced with "dummy.png", and without yet having taken a detailed look at the pybind11 bindings, can't for the life of me work out why some load fine and others do not. 

```
Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:24:40) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
🐍 🖥 ↴
import pymeshlab, sys
🐍 🖥 ↴
canvas = pymeshlab.MeshSet()
🐍 🖥 ↴
canvas.load_new_mesh('text.obj')
🐍 🖥 ↴
canvas.current_mesh().textures()
{'dummy.png': <pymeshlab.pmeshlab.Image object at 0x7f90903fb7f0>}
🐍 🖥 ↴
```
Have tried 2023.12.post2 and 2023.12, which matches the flatpak I have installed. This affects GLB/GLTF too.

**Comment by Serenity10086** [comment]
> I am able to load meshes fine in the GUI. When I load from python, I keep seeing it replaced with "dummy.png", and without yet having taken a detailed look at the pybind11 bindings, can't for the life of me work out why some load fine and others do not.
> 
> ```
> Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:24:40) [GCC 13.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 🐍 🖥 ↴
> import pymeshlab, sys
> 🐍 🖥 ↴
> canvas = pymeshlab.MeshSet()
> 🐍 🖥 ↴
> canvas.load_new_mesh('text.obj')
> 🐍 🖥 ↴
> canvas.current_mesh().textures()
> {'dummy.png': <pymeshlab.pmeshlab.Image object at 0x7f90903fb7f0>}
> 🐍 🖥 ↴
> ```
> 
> Have tried 2023.12.post2 and 2023.12, which matches the flatpak I have installed. This affects GLB/GLTF too.

I think you can take a look at this comment, maybe it can help you.
https://github.com/cnr-isti-vclab/PyMeshLab/issues/294#issuecomment-2194468487
