### ISSUE TITLE
import Error RichFileSave

### ISSUE THREAD

**Issue by CanCanZeng** [cnr-isti-vclab/PyMeshLab#374]
my system is ubuntu20.04 with intel CPU, and I use conda python env.
pythonr version tried 3.7.13, 3.9.18 and 3.10, pymeshlab tried from 0.2.1 to latest 2023.12.post1, all of those raise import Error, the latest pymeshlab will say `ImportError: ~/miniconda3/envs/gof/lib/python3.9/site-packages/pymeshlab/pmeshlab.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTI12RichFileSave`  and older version will give many other error like `ImportError: /home/zcc/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/pymeshlab/pmeshlab.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN7meshlab16meshFromMatricesERKN5Eigen6MatrixIdLin1ELi3ELi0ELin1ELi3EEERKNS1_IiLin1ELi3ELi0ELin1ELi3EEERKNS1_IiLin1ELi2ELi0ELin1ELi2EEES4_S4_RKNS1_IdLin1ELi1ELi0ELin1ELi1EEESD_RKNS1_IdLin1ELi4ELi0ELin1ELi4EEESG_`
Help wanted!!!

**Comment by CanCanZeng** [comment]
Hi @alemuntoni  thank you for your reminder, I deactivated conda and still got this error:
```
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymeshlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /usr/local/lib/python3.8/dist-packages/pymeshlab/pmeshlab.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7meshlab16meshFromMatricesERKN5Eigen6MatrixIdLin1ELi3ELi0ELin1ELi3EEERKNS1_IiLin1ELi3ELi0ELin1ELi3EEERKNS1_IiLin1ELi2ELi0ELin1ELi2EEES4_S4_RKNS1_IdLin1ELi1ELi0ELin1ELi1EEESD_RKNS1_IdLin1ELi4ELi0ELin1ELi4EEESG_
```

**Comment by CanCanZeng** [comment]
I installed pymeshlab through `pip3 install pymeshlab`, and the default pymeshlab version is 2022.2.post3. I downloaded the latest pymeshlab-2023.12.post1-cp38-cp38-manylinux_2_31_x86_64.whl from https://pypi.org but cannot install: 
`ERROR: pymeshlab-2023.12.post1-cp38-cp38-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.`
